title: Project

status:
    draft: Draft
    listed: Published

tabs:

  # main content
  meta:
    label: 基本内容 ｜ INFO
    sections:
      content:
        type: fields

        fields:
          name:
            label: 标题 ｜ Title
            type: text

          tags:
            label: 标签 | Tags
            type: tags
            options: query
            query: page.siblings.pluck("tags", ",", true)

          intro:
            label: 简介 | Intro
            type: textarea
            size: medium
            minlength: 10
            maxlength: 500

          preview:
            label: 封面图 ｜ cover image
            type: files
            multiple: false
            query: page.images


          artist:
            label: 艺术家 ｜ 工作室
            type: structure
            fields:
              artistName:
                label: name
                type: text
              artistLink:
                label: 链接 ｜ link
                type: url

  # meta information
  content:
    label: 详细内容 ｜ Main Content

    columns:
      - width: 2/3
        sections:
          main:
            type: fields
            fields:
              main:
                label: 作品介绍
                type: textarea
                size: medium
              aboutArtist:
                label: 作者介绍
                type: textarea
                size: medium

      - width: 1/3
        sections:
          extra:
            type: fields
            fields:
              gallery:
                type: files
                query: page.images
              place:
                label: 地点
                type: text
              time:
                label: 时间
                type: date
