title: Main


tabs:

  # main content
  projects:
    label: 作品 ｜ projects
    columns:
      left:
        width: 2/3
        sections:
           pages:
             type: pages
             create: project
             templates:
               - project


      right:
        width: 1/3
        sections:
          draft:
            status: draft
            templates:
              - project



  artists:

  news:

  info:
